// backend/config.js — Central configuration for HK18 Prophet
import 'dotenv/config';

export const config = {
  // LLM Settings
  llm: {
    apiKey: process.env.LLM_API_KEY || '',
    baseUrl: process.env.LLM_BASE_URL || 'https://api.openai.com/v1',
    modelName: process.env.LLM_MODEL_NAME || 'gpt-4o-mini',
    agentTemperature: 0.4,
    moderatorTemperature: 0.2,
    agentMaxTokens: 2000,
    moderatorMaxTokens: 8000,
  },

  // Server
  server: {
    port: parseInt(process.env.PORT || '5001', 10),
    nodeEnv: process.env.NODE_ENV || 'development',
  },

  // Simulation
  simulation: {
    rounds: parseInt(process.env.SIMULATION_ROUNDS || '3', 10),
    maxConcurrentAgents: parseInt(process.env.MAX_CONCURRENT_AGENTS || '10', 10),
    districtBatchSize: 6,
  },

  // Cache
  cache: {
    ttlHours: parseFloat(process.env.CACHE_TTL_HOURS || '1'), // 1h dev, 24h for prod
  },

  // Rate limiting
  rateLimit: {
    customEstatePerHour: parseInt(process.env.RATE_LIMIT_CUSTOM_PER_HOUR || '10', 10),
    districtPerHour: parseInt(process.env.RATE_LIMIT_DISTRICT_PER_HOUR || '30', 10),
  },

  // Database
  db: {
    path: process.env.DB_PATH || './data/hk18prophet.db',
  },

  // News API
  newsApi: {
    key: process.env.NEWS_API_KEY || '',
    baseUrl: 'https://newsapi.org/v2',
  },

  // Hong Kong 18 Districts
  districts: [
    { code: 'CW', name: 'Central & Western', nameCn: '中西區', region: 'HK Island', keyAreas: ['Central', 'Sheung Wan', 'Sai Ying Pun', 'Mid-Levels', 'The Peak'], character: 'Premium CBD, luxury residential, expat hub', priceRange: [15000, 35000], keyDrivers: ['CBD proximity', 'luxury demand', 'expat flow', 'MTR connectivity'], majorEstates: [
      { name: 'The Belcher\'s', nameCn: '寶翠園', area: 'Kennedy Town' },
      { name: 'Island Crest', nameCn: '縉城峰', area: 'Sai Ying Pun' },
      { name: 'University Heights', nameCn: '大學閣', area: 'Mid-Levels West' },
      { name: 'Greenview Garden', nameCn: '翠景閣', area: 'Mid-Levels West' },
      { name: 'Scenic Heights', nameCn: '荊蘭閣', area: 'Mid-Levels West' },
      { name: 'Robinson Place', nameCn: '雍景臺', area: 'Mid-Levels' },
      { name: 'Imperial Court', nameCn: '帝豪閣', area: 'Mid-Levels' },
      { name: 'Conduit Tower', nameCn: '干德道38號', area: 'Mid-Levels' },
      { name: 'Townplace Kennedy Town', nameCn: '本舍', area: 'Kennedy Town' },
      { name: 'The Summa', nameCn: '高士台', area: 'Sai Ying Pun' },
    ] },
    { code: 'WC', name: 'Wan Chai', nameCn: '灣仔', region: 'HK Island', keyAreas: ['Wan Chai', 'Causeway Bay', 'Happy Valley', 'Tai Hang'], character: 'Mixed commercial-residential, vibrant nightlife, conventions', priceRange: [14000, 30000], keyDrivers: ['commercial activity', 'convention centre', 'Happy Valley premium', 'MTR access'], majorEstates: [
      { name: 'The Leighton Hill', nameCn: '禮頓山', area: 'Causeway Bay' },
      { name: 'Bamboo Grove', nameCn: '嘉崙臺', area: 'Wan Chai' },
      { name: 'Star Crest', nameCn: '星域軒', area: 'Wan Chai' },
      { name: 'The Avenue', nameCn: '囍匯', area: 'Wan Chai' },
      { name: 'J Residence', nameCn: '嘉薈軒', area: 'Wan Chai' },
      { name: 'Tai Hang Terrace', nameCn: '大坑台', area: 'Tai Hang' },
      { name: 'Park Haven', nameCn: '曦巒', area: 'Causeway Bay' },
      { name: 'yoo Residence', nameCn: 'yoo Residence', area: 'Causeway Bay' },
      { name: 'Ventris Place', nameCn: '雲地利台', area: 'Happy Valley' },
      { name: 'Broadwood Twelve', nameCn: '樂天峰', area: 'Happy Valley' },
    ] },
    { code: 'EA', name: 'Eastern', nameCn: '東區', region: 'HK Island', keyAreas: ['North Point', 'Quarry Bay', 'Taikoo', 'Shau Kei Wan', 'Chai Wan'], character: 'Mature residential, good transport, mixed-income', priceRange: [10000, 22000], keyDrivers: ['Island East office corridor', 'MTR coverage', 'school networks', 'redevelopment'], majorEstates: [
      { name: 'Taikoo Shing', nameCn: '太古城', area: 'Tai Koo' },
      { name: 'Kornhill', nameCn: '康怡花園', area: 'Quarry Bay' },
      { name: 'City Garden', nameCn: '城市花園', area: 'North Point' },
      { name: 'Healthy Village', nameCn: '健康村', area: 'North Point' },
      { name: 'Grand Promenade', nameCn: '嘉亨灣', area: 'Sai Wan Ho' },
      { name: 'Lei King Wan', nameCn: '鯉景灣', area: 'Sai Wan Ho' },
      { name: 'Heng Fa Chuen', nameCn: '杏花邨', area: 'Chai Wan' },
      { name: 'Provident Centre', nameCn: '和富中心', area: 'North Point' },
      { name: 'Harbour Heights', nameCn: '海峰園', area: 'North Point' },
      { name: 'Mount Parker Residences', nameCn: '柏蔚山', area: 'Quarry Bay' },
    ] },
    { code: 'SO', name: 'Southern', nameCn: '南區', region: 'HK Island', keyAreas: ['Aberdeen', 'Ap Lei Chau', 'Repulse Bay', 'Stanley', 'Pok Fu Lam'], character: 'Diverse — luxury coastal + public housing, Ocean Park', priceRange: [8000, 35000], keyDrivers: ['South Island Line', 'luxury coastal demand', 'Ocean Park', 'tech hub Wong Chuk Hang'], majorEstates: [
      { name: 'South Horizons', nameCn: '海怡半島', area: 'Ap Lei Chau' },
      { name: 'Larvotto', nameCn: '南灣', area: 'Ap Lei Chau' },
      { name: 'Marinella', nameCn: '深灣9號', area: 'Wong Chuk Hang' },
      { name: 'Wong Chuk Hang Station Development (The Southside)', nameCn: '黃竹坑站項目 (港島南岸)', area: 'Wong Chuk Hang' },
      { name: 'Chi Fu Fa Yuen', nameCn: '置富花園', area: 'Pok Fu Lam' },
      { name: 'Bel-Air', nameCn: '貝沙灣', area: 'Pok Fu Lam' },
      { name: 'Residence Bel-Air', nameCn: '貝沙灣', area: 'Pok Fu Lam' },
      { name: 'Aberdeen Centre', nameCn: '香港仔中心', area: 'Aberdeen' },
      { name: 'South Wave Court', nameCn: '南濤閣', area: 'Ap Lei Chau' },
      { name: 'The Repulse Bay', nameCn: '影灣園', area: 'Repulse Bay' },
    ] },
    { code: 'YTM', name: 'Yau Tsim Mong', nameCn: '油尖旺', region: 'Kowloon', keyAreas: ['Tsim Sha Tsui', 'Jordan', 'Yau Ma Tei', 'Mong Kok', 'Olympic'], character: 'Tourist/shopping hub, dense urban, high rental yield', priceRange: [11000, 25000], keyDrivers: ['tourism recovery', 'retail activity', 'MTR hub', 'urban density'], majorEstates: [
      { name: 'The Waterfront', nameCn: '維港灣', area: 'Tsim Sha Tsui' },
      { name: 'The Harbourside', nameCn: '君臨天下', area: 'Olympic' },
      { name: 'Sorrento', nameCn: '擎天半島', area: 'Olympic' },
      { name: 'The Arch', nameCn: '凱旋門', area: 'Olympic' },
      { name: 'One West Kowloon', nameCn: '匯璽', area: 'Olympic' },
      { name: 'Island Harbourview', nameCn: '維港灣', area: 'Olympic' },
      { name: 'MASTERPIECE', nameCn: '名鑄', area: 'Tsim Sha Tsui' },
      { name: 'The Austin', nameCn: '柯士甸站上蓋', area: 'Jordan' },
      { name: 'Prosperous Garden', nameCn: '富榮花園', area: 'Mong Kok' },
      { name: 'Metro Harbour View', nameCn: '都會海逸', area: 'Tai Kok Tsui' },
    ] },
    { code: 'SSP', name: 'Sham Shui Po', nameCn: '深水埗', region: 'Kowloon', keyAreas: ['Sham Shui Po', 'Cheung Sha Wan', 'Lai Chi Kok', 'Mei Foo'], character: 'Working-class heritage, gentrifying rapidly, tech startups', priceRange: [8000, 16000], keyDrivers: ['gentrification', 'affordability gap', 'Mei Foo premium', 'young professional influx'], majorEstates: [
      { name: 'Mei Foo Sun Chuen', nameCn: '美孚新邨', area: 'Mei Foo' },
      { name: 'Banyan Garden', nameCn: '泓景臺', area: 'Lai Chi Kok' },
      { name: 'Liberté', nameCn: '昇悅居', area: 'Lai Chi Kok' },
      { name: 'Vista', nameCn: '海峰', area: 'Lai Chi Kok' },
      { name: 'Un Chau Estate', nameCn: '元州邨', area: 'Sham Shui Po' },
      { name: 'Nam Cheong Station Development', nameCn: '匯璽', area: 'Nam Cheong' },
      { name: 'The Pacifica', nameCn: '一號‧西九龍', area: 'Cheung Sha Wan' },
      { name: 'Aqua Marine', nameCn: '星匯海', area: 'Cheung Sha Wan' },
      { name: 'Carnival Mansion', nameCn: '嘉年華商場', area: 'Sham Shui Po' },
      { name: 'Trinity Towers', nameCn: '丰匯', area: 'Lai Chi Kok' },
    ] },
    { code: 'KC', name: 'Kowloon City', nameCn: '九龍城', region: 'Kowloon', keyAreas: ['Kowloon City', 'Kowloon Tong', 'Ho Man Tin', 'To Kwa Wan', 'Kai Tak'], character: 'School belt premium, Kai Tak new development area', priceRange: [10000, 25000], keyDrivers: ['Kai Tak development', 'school belt (Kowloon Tong)', 'Shatin-Central Link', 'cruise terminal'], majorEstates: [
      { name: 'Parc City', nameCn: '啟德1號', area: 'Kai Tak' },
      { name: 'OASIS KAI TAK', nameCn: '啟德沐泰街12號', area: 'Kai Tak' },
      { name: 'Monaco', nameCn: 'MONACO', area: 'Kai Tak' },
      { name: 'Mantin Heights', nameCn: '皓畋', area: 'Ho Man Tin' },
      { name: 'Ultima', nameCn: '天鑄', area: 'Ho Man Tin' },
      { name: 'Festival City', nameCn: '聖德肋撒', area: 'Kowloon Tong' },
      { name: 'Beacon Heights', nameCn: '畢架山花園', area: 'Kowloon Tong' },
      { name: 'Wyler Gardens', nameCn: '偉恒昌新邨', area: 'To Kwa Wan' },
      { name: 'Grand Waterfront', nameCn: '翔龍灣', area: 'To Kwa Wan' },
      { name: 'Victoria Skye', nameCn: '天寰', area: 'Kai Tak' },
    ] },
    { code: 'WTS', name: 'Wong Tai Sin', nameCn: '黃大仙', region: 'Kowloon', keyAreas: ['Wong Tai Sin', 'Diamond Hill', 'Tsz Wan Shan', 'San Po Kong'], character: 'Traditional public housing, temple tourism, improving transport', priceRange: [8000, 15000], keyDrivers: ['MTR extensions', 'Diamond Hill development', 'affordability', 'estate renewal'], majorEstates: [
      { name: 'Galaxia', nameCn: '星河明居', area: 'Diamond Hill' },
      { name: 'Mikiki (residential portion)', nameCn: '新蒲崗新盤', area: 'San Po Kong' },
      { name: 'Plaza Hollywood (residential)', nameCn: '荷里活廣場', area: 'Diamond Hill' },
      { name: 'Sceneway Garden', nameCn: '景泰苑', area: 'Lam Tin' },
      { name: 'Tsz Ching Estate', nameCn: '慈正邨', area: 'Tsz Wan Shan' },
      { name: 'Choi Hung Estate', nameCn: '彩虹邨', area: 'Choi Hung' },
      { name: 'Fung Tak Estate', nameCn: '鳳德邨', area: 'Diamond Hill' },
      { name: 'San Po Kong Plaza', nameCn: '新蒲崗廣場', area: 'San Po Kong' },
      { name: 'Tropicana Garden', nameCn: '太子花園', area: 'Diamond Hill' },
      { name: 'Lung Poon Court', nameCn: '龍蟠苑', area: 'Diamond Hill' },
    ] },
    { code: 'KT', name: 'Kwun Tong', nameCn: '觀塘', region: 'Kowloon', keyAreas: ['Kwun Tong', 'Lam Tin', 'Yau Tong', 'Kowloon Bay', 'Ngau Tau Kok'], character: 'Former industrial, rapid commercial conversion, CBD2 vision', priceRange: [8000, 16000], keyDrivers: ['industrial conversion', 'CBD2 office supply', 'MTR connectivity', 'affordable entry'], majorEstates: [
      { name: 'Laguna City', nameCn: '麗港城', area: 'Cha Kwo Ling' },
      { name: 'Sceneway Garden', nameCn: '滙景花園', area: 'Lam Tin' },
      { name: 'Amoy Gardens', nameCn: '淘大花園', area: 'Kowloon Bay' },
      { name: 'Telford Gardens', nameCn: '德福花園', area: 'Kowloon Bay' },
      { name: 'Yau Tong Centre', nameCn: '油塘中心', area: 'Yau Tong' },
      { name: 'OCEAN ONE', nameCn: 'OCEAN ONE', area: 'Yau Tong' },
      { name: 'Peninsula East', nameCn: '東環', area: 'Yau Tong' },
      { name: 'Kwun Tong View', nameCn: '觀塘中心', area: 'Kwun Tong' },
      { name: 'Domain', nameCn: '鬼域', area: 'Yau Tong' },
      { name: 'Canaryside', nameCn: '啟岸', area: 'Kwun Tong' },
    ] },
    { code: 'KI', name: 'Kwai Tsing', nameCn: '葵青', region: 'New Territories', keyAreas: ['Kwai Fong', 'Kwai Chung', 'Tsing Yi'], character: 'Container port area, affordable, good transport links', priceRange: [7000, 13000], keyDrivers: ['affordability', 'Tsing Yi bridge links', 'container port activity', 'MTR access'], majorEstates: [
      { name: 'Mayfair Gardens', nameCn: '美孚新邨', area: 'Kwai Fong' },
      { name: 'Greenfield Garden', nameCn: '翠怡花園', area: 'Tsing Yi' },
      { name: 'Cheung Fat Estate', nameCn: '長發邨', area: 'Tsing Yi' },
      { name: 'Tierra Verde', nameCn: '盈翠半島', area: 'Tsing Yi' },
      { name: 'Tsing Yi Garden', nameCn: '青衣花園', area: 'Tsing Yi' },
      { name: 'Rambler Crest', nameCn: '青嶼半島', area: 'Tsing Yi' },
      { name: 'New Kwai Fong Gardens', nameCn: '新葵芳花園', area: 'Kwai Fong' },
      { name: 'Kwai Chung Estate', nameCn: '葵涌邨', area: 'Kwai Chung' },
      { name: 'Lai King Estate', nameCn: '荔景邨', area: 'Lai King' },
      { name: 'Wonderland Villas', nameCn: '華景山莊', area: 'Kwai Fong' },
    ] },
    { code: 'TW', name: 'Tsuen Wan', nameCn: '荃灣', region: 'New Territories', keyAreas: ['Tsuen Wan', 'Tsuen King Garden', 'Belvedere Garden', 'Discovery Park'], character: 'Mature NT town, good shopping, gateway to Lantau', priceRange: [8000, 16000], keyDrivers: ['transport hub', 'established community', 'proximity to airport', 'hiking/nature access'], majorEstates: [
      { name: 'Belvedere Garden', nameCn: '麗城花園', area: 'Tsuen Wan West' },
      { name: 'Discovery Park', nameCn: '探索薈', area: 'Tsuen Wan' },
      { name: 'Tsuen King Garden', nameCn: '荃景花園', area: 'Tsuen Wan' },
      { name: 'Clague Garden Estate', nameCn: '祈德尊新邨', area: 'Tsuen Wan' },
      { name: 'Allway Garden', nameCn: '荃灣花園', area: 'Tsuen Wan' },
      { name: 'Riviera Garden', nameCn: '海濱花園', area: 'Tsuen Wan West' },
      { name: 'The Pavilia Bay', nameCn: '柏傲灣', area: 'Tsuen Wan West' },
      { name: 'Ocean Pride', nameCn: '海之戀', area: 'Tsuen Wan West' },
      { name: 'Bayview Garden', nameCn: '灣景花園', area: 'Tsuen Wan' },
      { name: 'Vision City', nameCn: '萬景峯', area: 'Tsuen Wan' },
    ] },
    { code: 'TM', name: 'Tuen Mun', nameCn: '屯門', region: 'New Territories', keyAreas: ['Tuen Mun', 'Gold Coast', 'So Kwun Wat', 'Hung Shui Kiu'], character: 'Suburban, large estates, light rail, Shenzhen proximity', priceRange: [5000, 12000], keyDrivers: ['Hung Shui Kiu development', 'Tuen Ma Line', 'affordability', 'GBA connectivity'], majorEstates: [
      { name: 'Siu Hong Court', nameCn: '兆康苑', area: 'Siu Hong' },
      { name: 'Tuen Mun Town Plaza', nameCn: '屯門市廣場', area: 'Tuen Mun' },
      { name: 'Gold Coast', nameCn: '黃金海岸', area: 'So Kwun Wat' },
      { name: 'Aegean Coast', nameCn: '愛琴海岸', area: 'So Kwun Wat' },
      { name: 'Sam Shing Estate', nameCn: '三聖邨', area: 'Tuen Mun' },
      { name: 'Melody Garden', nameCn: '美樂花園', area: 'Tuen Mun' },
      { name: 'Leung King Estate', nameCn: '良景邨', area: 'Tuen Mun' },
      { name: 'On Ting Estate', nameCn: '安定邨', area: 'Tuen Mun' },
      { name: 'Lung Mun Oasis', nameCn: '龍門居', area: 'Tuen Mun' },
      { name: 'Chelsea Court', nameCn: '荃灣花園', area: 'Tuen Mun' },
    ] },
    { code: 'YL', name: 'Yuen Long', nameCn: '元朗', region: 'New Territories', keyAreas: ['Yuen Long', 'Tin Shui Wai', 'Hung Shui Kiu', 'Fairview Park'], character: 'Fastest growing NT area, massive new supply, Shenzhen border', priceRange: [5000, 13000], keyDrivers: ['Northern Metropolis', 'new town development', 'Shenzhen border proximity', 'massive new supply'], majorEstates: [
      { name: 'YOHO Town', nameCn: 'YOHO Town', area: 'Yuen Long' },
      { name: 'YOHO Midtown', nameCn: 'YOHO Midtown', area: 'Yuen Long' },
      { name: 'Grand YOHO', nameCn: 'Grand YOHO', area: 'Yuen Long' },
      { name: 'Park YOHO', nameCn: 'Park YOHO', area: 'Yuen Long' },
      { name: 'Fairview Park', nameCn: '錦繡花園', area: 'Yuen Long' },
      { name: 'Kingswood Villas', nameCn: '嘉湖山莊', area: 'Tin Shui Wai' },
      { name: 'Tin Yuet Estate', nameCn: '天悅邨', area: 'Tin Shui Wai' },
      { name: 'Ying Tung Estate', nameCn: '映都', area: 'Yuen Long' },
      { name: 'The Reach', nameCn: '尚悅', area: 'Yuen Long South' },
      { name: 'Residence 88', nameCn: '采葉庭', area: 'Yuen Long' },
    ] },
    { code: 'NO', name: 'North', nameCn: '北區', region: 'New Territories', keyAreas: ['Sheung Shui', 'Fanling', 'Kwu Tung', 'Ping Che'], character: 'Border district, Northern Metropolis centerpiece, rural + urban', priceRange: [5000, 12000], keyDrivers: ['Northern Metropolis Strategy', 'innovation & tech zone', 'Shenzhen integration', 'new railway links'], majorEstates: [
      { name: 'Royal Green', nameCn: '御皇庭', area: 'Fanling' },
      { name: 'Fanling Centre', nameCn: '粉嶺中心', area: 'Fanling' },
      { name: 'Regentville', nameCn: '皇府山', area: 'Fanling' },
      { name: 'Vienna Garden', nameCn: '維也納花園', area: 'Sheung Shui' },
      { name: 'Sheung Shui Town Centre', nameCn: '上水中心', area: 'Sheung Shui' },
      { name: 'Landmark North', nameCn: '上水廣場', area: 'Sheung Shui' },
      { name: 'Avon Park', nameCn: '海典居', area: 'Fanling' },
      { name: 'Wing Fai Centre', nameCn: '榮輝中心', area: 'Sheung Shui' },
      { name: 'Flora Plaza', nameCn: '花都廣場', area: 'Fanling' },
      { name: 'Dawning Views', nameCn: '曉翠山莊', area: 'Fanling' },
    ] },
    { code: 'TP', name: 'Tai Po', nameCn: '大埔', region: 'New Territories', keyAreas: ['Tai Po', 'Tai Po Market', 'Science Park', 'CUHK area'], character: 'University town, science park, cycling paradise, nature', priceRange: [6000, 14000], keyDrivers: ['Science Park expansion', 'CUHK/education hub', 'quality of life', 'limited new supply'], majorEstates: [
      { name: 'Deerhill Bay', nameCn: '鹿茵山莊', area: 'Tai Po' },
      { name: 'Tai Po Centre', nameCn: '大埔中心', area: 'Tai Po' },
      { name: 'Uptown Plaza', nameCn: '新達廣場', area: 'Tai Po' },
      { name: 'On Tai Estate', nameCn: '安泰邨', area: 'Tai Po' },
      { name: 'Tai Po Garden', nameCn: '大埔花園', area: 'Tai Po' },
      { name: 'Parc Versailles', nameCn: '翡翠花園', area: 'Tai Po' },
      { name: 'Lake Silver', nameCn: '銀湖‧天峰', area: 'Wu Kai Sha' },
      { name: 'Bright Star Mansion', nameCn: '明星樓', area: 'Tai Po Market' },
      { name: 'Scenic Panorama', nameCn: '新峰花園', area: 'Tai Po' },
      { name: 'The Palazzo', nameCn: '嵐山', area: 'Tai Po' },
    ] },
    { code: 'ST', name: 'Sha Tin', nameCn: '沙田', region: 'New Territories', keyAreas: ['Sha Tin', 'Ma On Shan', 'Fo Tan', 'City One', 'Sha Tin Wai'], character: 'Largest NT town, excellent facilities, racecourse', priceRange: [8000, 18000], keyDrivers: ['Sha Tin-Central Link completed', 'Ma On Shan premium', 'university proximity', 'mature infrastructure'], majorEstates: [
      { name: 'City One Shatin', nameCn: '沙田第一城', area: 'Sha Tin' },
      { name: 'Lek Yuen Estate', nameCn: '瀝源邨', area: 'Sha Tin' },
      { name: 'Jubilee Garden', nameCn: '銀禧花園', area: 'Sha Tin' },
      { name: 'Festival City', nameCn: '名城', area: 'Sha Tin' },
      { name: 'Sunshine City', nameCn: '新港城', area: 'Ma On Shan' },
      { name: 'Bayshore Towers', nameCn: '海典灣', area: 'Ma On Shan' },
      { name: 'Lake Silver', nameCn: '銀湖天峰', area: 'Ma On Shan' },
      { name: 'Double Cove', nameCn: '迎海', area: 'Ma On Shan' },
      { name: 'Fo Tan Station Development', nameCn: '火炭站上蓋', area: 'Fo Tan' },
      { name: 'Sha Tin Heights', nameCn: '沙田嶺', area: 'Sha Tin' },
    ] },
    { code: 'SK', name: 'Sai Kung', nameCn: '西貢', region: 'New Territories', keyAreas: ['Tseung Kwan O', 'Sai Kung Town', 'Clear Water Bay', 'LOHAS Park'], character: 'TKO new town + Sai Kung countryside, growing rapidly', priceRange: [7000, 16000], keyDrivers: ['TKO expansion', 'LOHAS Park development', 'Cross Bay Link', 'nature/lifestyle appeal'], majorEstates: [
      { name: 'LOHAS Park', nameCn: '日出康城', area: 'Tseung Kwan O' },
      { name: 'Park Central', nameCn: '將軍澳中心', area: 'Tseung Kwan O' },
      { name: 'PopCorn (residential)', nameCn: 'PopCorn住宅', area: 'Tseung Kwan O' },
      { name: 'Oscar by the Sea', nameCn: '清水灣半島', area: 'Tseung Kwan O' },
      { name: 'The Wings', nameCn: '天晉', area: 'Tseung Kwan O' },
      { name: 'Tseung Kwan O Plaza', nameCn: '將軍澳廣場', area: 'Tseung Kwan O' },
      { name: 'Metro Town', nameCn: '都會駅', area: 'Tseung Kwan O' },
      { name: 'Savannah', nameCn: '領都', area: 'Tseung Kwan O' },
      { name: 'Century Link', nameCn: 'Century Link', area: 'Tseung Kwan O' },
      { name: 'Hemera', nameCn: '嵐岸', area: 'Sai Kung' },
    ] },
    { code: 'IS', name: 'Islands', nameCn: '離島', region: 'New Territories', keyAreas: ['Tung Chung', 'Discovery Bay', 'Mui Wo', 'Cheung Chau', 'Peng Chau'], character: 'Airport + Disneyland + rural islands, Tung Chung expanding massively', priceRange: [5000, 14000], keyDrivers: ['Tung Chung New Town expansion', 'airport/SkyCity commercial', '3rd runway effects', 'Lantau Tomorrow Vision'], majorEstates: [
      { name: 'Caribbean Coast', nameCn: '映灣園', area: 'Tung Chung' },
      { name: 'Tung Chung Crescent', nameCn: '東堤灣畔', area: 'Tung Chung' },
      { name: 'Coastal Skyline', nameCn: '藍天海岸', area: 'Tung Chung' },
      { name: 'Seaview Crescent', nameCn: '海堤灣畔', area: 'Tung Chung' },
      { name: 'The Visionary', nameCn: '昇薈', area: 'Tung Chung' },
      { name: 'Discovery Bay', nameCn: '愉景灣', area: 'Discovery Bay' },
      { name: 'Auberge Discovery Bay', nameCn: '愉景灣酒店', area: 'Discovery Bay' },
      { name: 'ONETERRACES', nameCn: 'ONETERRACES', area: 'Tung Chung' },
      { name: 'Mui Wo', nameCn: '梅窩', area: 'Mui Wo' },
      { name: 'Century Link', nameCn: '東環', area: 'Tung Chung' },
    ] },
  ],
};

export default config;
